#!/bin/bash
set -a

# Compiler and architecture settings
FC=""
CC=""
FFLAGS=""
USR_LFLAGS=""
ar=""

# Fetch version information for user reference
N_VERSION=$(git -C $NEK_SOURCE_ROOT describe --tag --long --always)
NS_VERSION=$(git -C $NEKLAB_SOURCE_ROOT describe --tag --long --always)

#-------------------------------------------------------------------------------
# Compiler Detection
#-------------------------------------------------------------------------------
if command -v mpiifort >/dev/null 2>&1; then
    # Intel compiler found
    echo "Intel compiler found: $(mpiifort -v)"
    FC="mpiifort"
    CC="mpiicc"
    FFLAGS+=" -extend-source" # Enables long lines.
    FFLAGS+=" -fixed" # Enables fixed-form source code, necessary as we mix .f90 files.
    
    if [[ $(mpiicx --version 2>&1) =~ "oneapi" ]]; then
        FFLAGS+=" -qmkl"
        CC="mpiicx"
        CFLAGS+=" -w"
    else
        FFLAGS+=" -mkl -xHost"
    fi

    FFLAGS+=" -g -traceback"
    USR_LFLAGS+=" -I${MKLROOT}/include -Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_intel_ilp64.a ${MKLROOT}/lib/intel64/libmkl_sequential.a ${MKLROOT}/lib/intel64/libmkl_core.a -Wl,--end-group -lpthread -lm -ldl"
else
    if [[ "$(uname)" == "Darwin" ]]; then
        # On macOS with Homebrew's mpif90
        if [[ -f "/opt/homebrew/bin/mpif90" ]]; then
            echo "Homebrew mpif90 found"
            FC="/opt/homebrew/bin/mpif90"
        else
            echo "Clang compiler found: $(clang --version | head -n1)"
        fi
    else
        # On Linux, we expect gcc to be gcc
        echo "GCC compiler found: $(gcc --version | head -n1)"
    fi
    FC="mpifort"
    CC="mpicc"
    FFLAGS+=" -ffixed-form" # Enables fixed-form source code, necessary as we mix .f90 files.
    FFLAGS+=" -ffixed-line-length-none" # Allows for any line length in fixed-form source code.
    FFLAGS+=" -march=native" # Enables all instruction subsets supported by the local machine.
    FFLAGS+=" -mtune=native" # Enables all instruction subsets supported by the local machine.
    FFLAGS+=" -g" # Enables debugging information.
    FFLAGS+=" -fbacktrace" # Provides a backtrace in case of errors, useful for debugging.
    FFLAGS+=" -std=legacy -Wall" # Provides a backtrace in case of errors, useful for debugging.
    
fi

CFLAGS+=" -w" # Disable warnings for C compiler

#-------------------------------------------------------------------------------
# Linking with LAPACK and BLAS
#-------------------------------------------------------------------------------

export PPLIST="VENDOR_BLAS"

# Lapack is a library of linear algebra routines.
# Blas (Basic Linear Algebra Subprograms) is used by Lapack.

if [[ $(uname -s) == "Darwin" ]]; then
    USR_LFLAGS+=" -framework Accelerate"
else
    USR_LFLAGS+=" -llapack -lblas"
fi

#export USR_LFLAGS+=" -L/usr/local/opt/openblas/lib"
#export FFLAGS+=" -I/usr/local/opt/openblas/include"
#export USR_LFLAGS+=" -lopenblas" # OpenBlas is a faster alternative to LAPACK and BLAS

#-------------------------------------------------------------------------------
# Linking with LightKrylov library
#-------------------------------------------------------------------------------
export USR_LFLAGS+=" -lLightKrylov"
export USR_LFLAGS+=" -L$HOME/.local/lib -lLightKrylov"
export FFLAGS+=" -I$HOME/.local/include"

#-------------------------------------------------------------------------------
# Architecture Detection
#-------------------------------------------------------------------------------
case $(uname -s) in
    Darwin)
        case $(uname -p) in
            x86_64) ar="x86_64" ;;
            arm)    ar="arm" ;; # not compatile with mcmodel=large
        esac
        ;;
    Linux)
        case $(uname -p) in
            x86_64) ar="x86_64"; FFLAGS+=" -mcmodel=large" ;;
            arm)    ar="arm" ;;
        esac
        ;;
esac

#-------------------------------------------------------------------------------
# Final Preparations
#-------------------------------------------------------------------------------
FFLAGS+=" -DNVERSION=\"'${N_VERSION}'\" -DNSVERSION=\"'${NS_VERSION}'\""
export FFLAGS

# Update makefile and static variables
echo "include $NEKLAB_SOURCE_ROOT/src/makefile_neklab" > makefile_usr.inc

# User-specified object files
USR_NEKLAB="neklab_vectors.o"
USR_NEKLAB+=" real_vectors.o"
USR_NEKLAB+=" real_extended_vectors.o"
USR_NEKLAB+=" complex_vectors.o"
USR_NEKLAB+=" neklab_newton_control.o"
USR_NEKLAB+=" bf_buffer_io.o"
USR_NEKLAB+=" neklab_bf_buffer.o"
USR_NEKLAB+=" neklab_2Dh_axisym.o"
USR_NEKLAB+=" neklab_utils.o"
USR_NEKLAB+=" neklab_nek_setup.o"
USR_NEKLAB+=" neklab_nek_forcing.o"
USR_NEKLAB+=" neklab_2Dh.o"
USR_NEKLAB+=" neklab_helix.o"
USR_NEKLAB+=" helix_io.o"
USR_NEKLAB+=" helix_utils.o"
USR_NEKLAB+=" helix_gs.o"
USR_NEKLAB+=" helix_2d.o"
USR_NEKLAB+=" helix_mflow_fft.o"
USR_NEKLAB+=" neklab_linops.o"
USR_NEKLAB+=" exponential_propagator.o"
USR_NEKLAB+=" exponential_propagator_2Dh.o"
USR_NEKLAB+=" floquet_operator_torus.o"
USR_NEKLAB+=" resolvent.o"
USR_NEKLAB+=" neklab_systems.o"
USR_NEKLAB+=" fixed_point.o"
USR_NEKLAB+=" fixed_point_torus.o"
USR_NEKLAB+=" fixed_point_torus_2Dh.o"
USR_NEKLAB+=" periodic_orbit.o"
USR_NEKLAB+=" periodic_orbit_torus.o"
USR_NEKLAB+=" periodic_orbit_torus_2Dh.o"
USR_NEKLAB+=" neklab_otd.o"
USR_NEKLAB+=" neklab_analysis.o"
USR_NEKLAB+=" neklab_analysis_torus.o"
USR_NEKLAB+=" neklab_analysis_torus_2Dh.o"
USR_NEKLAB+=" neklab.o"
# get casename from .usr file
CASENAME=`find *.usr | sed 's/\.usr$//g'`

if [[ $1 == "clean" ]]; then

   echo ""
   echo "#############################################################"
   echo "#                Clean neklab compilation                   #"
   echo "#############################################################"
   echo ""
   set +a -e
   set -o pipefail
   $NEK_SOURCE_ROOT/bin/nekconfig $@

else

   # Output summary of settings
   echo ""
   echo "  compilation script: $0"
   echo "  casename:           $CASENAME"
   echo "  Nek5000 version:    $N_VERSION"
   echo "  neklab version:     $NS_VERSION"
   echo "  preparing compilation with:"
   echo "      compiler:     $(which $FC)"
   echo "      flags:      $FFLAGS"
   echo "      link-flags: $USR_LFLAGS"

   # Compile dummy first
   echo ""
   echo "#############################################################"
   echo "#              Compiling base nek nek_dummy.usr             #"
   echo "#############################################################"
   echo ""
   mv $CASENAME.usr $CASENAME.usr_tmp
   cp $NEK_SOURCE_ROOT/short_tests/chan2d/chan2d.usr nek_dummy.usr

   set +a -e
   set -o pipefail
   $NEK_SOURCE_ROOT/bin/nekconfig $@
   $NEK_SOURCE_ROOT/bin/nekconfig -build-dep
   
   # Compile dummy in parallel
   make -j4 2>&1 | tee -a build.log
   
   # Compile full case in serial to avoid race condition
   echo "#############################################################"
   echo "#                  Compiling $CASENAME.usr"
   echo "#############################################################"
   echo ""
   echo "Add neklab specifics to compilation:"
   echo "        USR_NEKLAB = $USR_NEKLAB"
   echo ""
   USR=$USR_NEKLAB
   export USR
   $NEK_SOURCE_ROOT/bin/nekconfig $@
   rm -rf nek_dummy.usr
   cp $CASENAME.usr_tmp $CASENAME.usr

   set +a -e
   $NEK_SOURCE_ROOT/bin/nekconfig $@
   $NEK_SOURCE_ROOT/bin/nekconfig -build-dep

   # Compile dummy in serial
   make -j1 2>&1 | tee -a build.log
      
   set +o pipefail
   if [ $(ls *.mod 2>/dev/null | wc -l) -gt 0 ]; then
      mv *.mod obj
      mv *.smod obj 2>/dev/null || true
   fi
fi
